application sudoku


In [1]:
import tkinter as tk
from tkinter import messagebox
import numpy as np


def ok_board(board):
    for i in range(9):
        row_set = set()
        col_set = set()
        box_set = set()
        for j in range(9):
            # Vérification de la ligne
            if board[i][j] != 0 and board[i][j] in row_set:
                return False
            row_set.add(board[i][j])
            
            # Vérification de la colonne
            if board[j][i] != 0 and board[j][i] in col_set:
                return False
            col_set.add(board[j][i])
            
            # Vérification de la boîte 3x3
            row_offset = (i // 3) * 3
            col_offset = (i % 3) * 3
            if board[row_offset + j // 3][col_offset + j % 3] != 0 and board[row_offset + j // 3][col_offset + j % 3] in box_set:
                return False
            box_set.add(board[row_offset + j // 3][col_offset + j % 3])
    return True


def check_board_validity(entries):
    C = [[int(entry.get()) if entry.get() else 0 for entry in row] for row in entries]
    if ok_board(C):
        messagebox.showinfo("Validation", "La grille Sudoku est correcte!")
    else:
        messagebox.showerror("Erreur", "La grille Sudoku est incorrecte.")
        

def clear_entries(entries):
    for row in entries:
        for entry in row:
            entry.delete(0, tk.END)

def solve_sudoku(entries):
    initial_board = [[int(entry.get()) if entry.get() else 0 for entry in row] for row in entries]
    solution = np.array(initial_board)
    solve_sudoku_recursive(solution)
    print("Solution after solving:")
    print(solution)
    for i in range(9):
        for j in range(9):
            entries[i][j].delete(0, tk.END)
            entries[i][j].insert(0, str(solution[i][j]))

def solve_sudoku_recursive(board):
    empty_cell = find_empty_cell(board)
    if not empty_cell:
        return True
    row, col = empty_cell
    for num in range(1, 10):
        if is_valid_move(board, row, col, num):
            board[row][col] = num
            if solve_sudoku_recursive(board):
                return True
            board[row][col] = 0
    return False
    

def is_valid_move(board, row, col, num):
    # Check if num is not already in the current row, column, or 3x3 box
    return (
        not used_in_row(board, row, num)
        and not used_in_col(board, col, num)
        and not used_in_box(board, row - row % 3, col - col % 3, num)
    )

def used_in_row(board, row, num):
    return num in board[row]

def used_in_col(board, col, num):
    return num in [board[i][col] for i in range(9)]

def used_in_box(board, start_row, start_col, num):
    for i in range(3):
        for j in range(3):
            if board[i + start_row][j + start_col] == num:
                return True
    return False
    
def find_empty_cell(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return (i, j)
    return None

def main():
    root = tk.Tk()
    root.title("Sudoku")

    entries = [[None for _ in range(9)] for _ in range(9)]

    for i in range(9):
        for j in range(9):
            entry = tk.Entry(root, width=3, font=('Helvetica', 16), justify="center")
            entry.grid(row=i, column=j)
            entries[i][j] = entry

            if (i % 3 == 2 and i != 8) or (j % 3 == 2 and j != 8):
                entry.grid(padx=(0, 2), pady=(0, 2))
            if (i // 3 + j // 3) % 2 == 0:
                entry.config(bg='lightgray')
    check_button = tk.Button(root, text="Check", command=lambda: check_board_validity(entries))
    check_button.grid(row=9, column=3, pady=(10, 0))

    solve_button = tk.Button(root, text="Solve", command=lambda: solve_sudoku(entries))
    solve_button.grid(row=9, column=4, pady=(10, 0))

    clear_button = tk.Button(root, text="Clear", command=lambda: clear_entries(entries))
    clear_button.grid(row=9, column=5, pady=(10, 0))

    root.mainloop()

if __name__ == "__main__":
    main()


Solution after solving:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 4 2 9 7 8 5 3 1]
 [9 7 8 5 3 1 6 4 2]]
